### ISSUE TITLE
Azure DevOps pipelines is sensitive to stderr

### ISSUE THREAD

**Issue by xJom** [danielstocker/vsts-backup-data-extension#1]
When running the script in Azure DevOps 2019 Update 1, the pipeline will fail, due to git writing information through stderr.

I suggest we add $env:GIT_REDIRECT_STDERR = '2>&1' in the beginning of the PowerShell-scripts.

**Comment by danielstocker** [comment]
That seems very sensible, yes. 
Thanks @xJom I've merged this

**Comment by danielstocker** [comment]
Reopening this until the change is released (will kick the pipeline later today)

**Comment by danielstocker** [comment]
now complete
